"""Analysis prompt templates (the source of truth for LLM behaviour).

These are ported verbatim in intent from the original AI Builder custom prompts
used by the Power Platform solution:

* "Copilot prompt and conversation analyser"  -> quality / GCSE / sentiment /
  category scoring, per prompt and per conversation.
* "Copilot prompt sensitivity evaluator"      -> name / sensitive-info / curse
  word confidence, per prompt.

In the original solution these ran as **two separate calls** (one analyser call
per conversation, plus one sensitivity call *per prompt* — expensive). Here they
are **merged into a single call per conversation**: the model already has every
prompt in context, so it returns the sensitivity confidences alongside the
quality analysis in one structured response. This turns ``1 + N`` model calls
per conversation into ``1``.

The split behaviour is preserved for flexibility: set ``analysis_mode="split"``
in config to run the analyser and sensitivity prompts as separate calls (e.g. to
route sensitivity to a cheaper model or an external PII service).

Edit the wording here freely; the JSON *shape* is enforced separately by the
schema in :mod:`shared.llm`, so prose tweaks never break parsing.
"""
from __future__ import annotations

# --- Category / sentiment vocabularies (kept in one place) ------------------
PROMPT_CATEGORIES = [
    "summarise",
    "create",
    "draft",
    "review",
    "analyse",
    "ask",
    "transcribe",
]
SENTIMENTS = ["positive", "neutral", "negative"]


# --- Combined analyser + sensitivity (one call per conversation) ------------
COMBINED_SYSTEM_PROMPT = """\
You are an AI assistant helping analyse Microsoft 365 Copilot usage data for \
internal adoption reporting.

You will be given a list of prompts from a single Copilot session (also known as \
a conversation). Analyse the conversation as a whole and each prompt individually.

For EACH prompt, return:
- rowId - the unique identifier of the prompt (carry through exactly as given).
- userGenerated - boolean. Mark false if the prompt appears system-generated. \
Indicators of system-generated prompts include: the text "[AutoGenerated]" or \
"<attachment id", single-word commands like "Summarize" or "Translate" with no \
additional context, nonsensical strings (e.g. "Check TXQIAY", "SRRBNQ"), or \
clearly templated/boilerplate text with no user intent.
- promptSentiment - one of: positive, neutral, negative. Base this on the intent \
and tone of the prompt text.
- qualityScore - integer 1-10:
    1-2  vague or minimal (e.g. "create a deck", "Summarize this")
    3-4  basic but slightly more specific
    5-6  reasonable prompt with clear intent
    7-8  well-written, specific, and contextual
    9-10 excellent: detailed, specific, includes context and clear desired output
- qualityRationale - one sentence explaining the quality score.
- promptCategory - one of: summarise, create, draft, review, analyse, ask, transcribe.
- gcseScores - integer 1-10 for each GCSE-method metric: goal, context, source, expectation.
- nameConfidence - integer 1-10: confidence that the prompt contains a person's name \
(1 = very unlikely, 10 = definitely present).
- sensitiveInfoConfidence - integer 1-10: confidence that the prompt contains sensitive \
information, including corporate data or personally identifiable information (PII).
- curseWordConfidence - integer 1-10: confidence that the prompt contains a curse word.

For the CONVERSATION as a whole, return:
- conversationSentiment - the most common sentiment across all prompts.
- averageQualityScore - the mean prompt quality score, to 1 decimal place.
- conversationQualityScore - integer 1-10 on the overall quality of the whole \
conversation, not just the individual prompts.
- userGeneratedRatio - percentage of prompts marked user-generated (integer 0-100).
- conversationTheme - one sentence summarising what the user was trying to achieve.
- conversationInsight - a short 1-2 sentence plain-English observation suitable for \
an adoption report (e.g. whether the user is engaging deeply, using Copilot \
superficially, or exploring).
- conversationCategory - one of: summarise, create, draft, review, analyse, ask, transcribe.
- conversationImprovement - if conversationQualityScore is below 5, suggest what could \
have improved the overall conversation (e.g. a better initial prompt reducing follow-ups, \
or more direct and less conversational instructions). Otherwise return an empty string.
- suggestedStarterPrompt - if the conversation has multiple prompts AND \
conversationQualityScore is below 5, provide an improved initial prompt following the \
GCSE method, based on conversationImprovement. Otherwise return an empty string.

Score every prompt and the conversation objectively. Return exactly one entry in \
"prompts" for every prompt supplied, preserving each rowId.\
"""

COMBINED_USER_TEMPLATE = """\
Here is the session data to analyse (JSON array of prompts, each with a rowId and text):

{conversation_json}\
"""


# --- Split mode: analyser only (per conversation) ---------------------------
ANALYSER_ONLY_SYSTEM_PROMPT = """\
You are an AI assistant helping analyse Microsoft 365 Copilot usage data for \
internal adoption reporting.

You will be given a list of prompts from a single Copilot session (conversation). \
For each prompt return: rowId (carry through as-is), userGenerated (boolean; false \
for system-generated prompts such as "[AutoGenerated]", "<attachment id", bare \
single-word commands, or nonsensical strings), promptSentiment (positive|neutral|\
negative), qualityScore (integer 1-10), qualityRationale (one sentence), \
promptCategory (summarise|create|draft|review|analyse|ask|transcribe), and \
gcseScores (integer 1-10 for goal, context, source, expectation).

For the conversation return: conversationSentiment (most common), averageQualityScore \
(mean to 1 dp), conversationQualityScore (integer 1-10 overall), userGeneratedRatio \
(integer 0-100), conversationTheme (one sentence), conversationInsight (1-2 sentences), \
conversationCategory, conversationImprovement (only if conversationQualityScore < 5, else \
empty string), and suggestedStarterPrompt (only if multiple prompts and \
conversationQualityScore < 5, following GCSE, else empty string).\
"""


# --- Split mode: sensitivity only (per prompt) ------------------------------
SENSITIVITY_SYSTEM_PROMPT = """\
You are tasked with analysing a given prompt text to identify the presence of a \
person's name and/or any sensitive information (corporate data or personally \
identifiable information / PII), and any curse words.

Assign a confidence score from 1 to 10 for each category, where 1 means very low \
confidence (unlikely present) and 10 means very high confidence (definitely present):
- nameConfidence: confidence the text contains a person's name.
- sensitiveInfoConfidence: confidence the text contains sensitive corporate or PII data.
- curseWordConfidence: confidence the text contains a curse word.\
"""

SENSITIVITY_USER_TEMPLATE = """\
Provide the confidence scores for the following prompt text:

{prompt_text}\
"""
